from __future__ import annotations

# Sentinel Hub
SH_CLMS_CORINELC_COLLECTION_NAME = "byoc-cbdba844-f86d-41dc-95ad-b3f7f12535e9"
SH_CLMS_CORINELC_LOCAL_NAME = "clms-corinelc"
SH_CLMS_WATER_BODIES_COLLECTION_NAME = "byoc-62bf6f6a-c584-48a8-a739-0bc60efee54a"
SH_CLMS_WATER_BODIES_LOCAL_NAME = "clms-water-bodies"

# EODH
CEDA_ESACCI_LC_COLLECTION_NAME = "land_cover"
CEDA_ESACCI_LC_LOCAL_NAME = "esacci-globallc"
SENTINEL_2_L2A_COLLECTION_NAME = "sentinel-2-l2a"
SENTINEL_2_ARD_COLLECTION_NAME = "sentinel2_ard"
LOCAL_COLLECTION_NAME = "collection"

STAC_COLLECTIONS = {
    SENTINEL_2_L2A_COLLECTION_NAME,
    SENTINEL_2_ARD_COLLECTION_NAME,
}
